
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Entry txtMXN;
	private global::Gtk.Label label1;
	private global::Gtk.Label label3;
	private global::Gtk.Label label2;
	private global::Gtk.Entry txtCam;
	private global::Gtk.Entry txtUSD;
	private global::Gtk.Button button1;
	private global::Gtk.Button button2;
	private global::Gtk.Button button3;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Convertir");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtMXN = new global::Gtk.Entry ();
		this.txtMXN.CanFocus = true;
		this.txtMXN.Name = "txtMXN";
		this.txtMXN.Text = global::Mono.Unix.Catalog.GetString ("0");
		this.txtMXN.IsEditable = true;
		this.txtMXN.InvisibleChar = '•';
		this.fixed1.Add (this.txtMXN);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtMXN]));
		w1.X = 37;
		w1.Y = 56;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Pesos:");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w2.X = 35;
		w2.Y = 23;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = "Dolares:";
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w3.X = 42;
		w3.Y = 109;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Tipo Cambio:");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w4.X = 229;
		w4.Y = 24;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtCam = new global::Gtk.Entry ();
		this.txtCam.CanFocus = true;
		this.txtCam.Name = "txtCam";
		this.txtCam.Text = global::Mono.Unix.Catalog.GetString ("10.50");
		this.txtCam.IsEditable = true;
		this.txtCam.InvisibleChar = '•';
		this.fixed1.Add (this.txtCam);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtCam]));
		w5.X = 225;
		w5.Y = 52;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtUSD = new global::Gtk.Entry ();
		this.txtUSD.Sensitive = false;
		this.txtUSD.CanFocus = true;
		this.txtUSD.Name = "txtUSD";
		this.txtUSD.Text = global::Mono.Unix.Catalog.GetString ("0");
		this.txtUSD.IsEditable = true;
		this.txtUSD.InvisibleChar = '•';
		this.fixed1.Add (this.txtUSD);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtUSD]));
		w6.X = 34;
		w6.Y = 138;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Convertir");
		this.fixed1.Add (this.button1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button1]));
		w7.X = 206;
		w7.Y = 137;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Reset");
		this.fixed1.Add (this.button2);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button2]));
		w8.X = 288;
		w8.Y = 137;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("Salir");
		this.fixed1.Add (this.button3);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button3]));
		w9.X = 343;
		w9.Y = 137;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 417;
		this.DefaultHeight = 237;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
		this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
		this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
	}
}
